FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o generator ./cmd/generator

###

FROM alpine:3.20.0

LABEL maintainer="Sebastian Salata R-T <sa.salatart@gmail.com>"

WORKDIR /root/

COPY --from=builder /app/generator .
COPY --from=builder /app/config/config.yaml ./config/config.yaml

CMD ["./generator"]
