FROM golang:1.23

WORKDIR /app

ENV GOCACHE=/tmp/go-cache
RUN mkdir -p /tmp/go-cache && chmod -R 777 /tmp/go-cache

RUN go install github.com/air-verse/air@v1.52.3

CMD ["air", "-c", "./cmd/api/air.toml"]
