receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '0.0.0.0:4317'
      http:
        endpoint: '0.0.0.0:4318'

processors:
  batch:
    timeout: 5s

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  prometheus:
    endpoint: '0.0.0.0:9091' # Prometheus pulls metrics, it does not push

extensions:
  health_check:

service:
  extensions: [health_check]

  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
