db:
  url: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable

llm:
  openai_key: 'expose me as LLM_OPENAI_KEY env var'
  questions:
    batch_size: 8
    frequency: '12h'

server:
  host: 'quizory'
  rest_port: 8080
  grpc_port: 8085
  read_timeout: '5s'
  write_timeout: '5s'
  jwt_secret: 'expose me as SERVER_JWT_SECRET en var'
