// Code generated by "enumer -type=Topic -trimprefix=Topic -transform=whitespace"; DO NOT EDIT.

package enums

import (
	"fmt"
	"strings"
)

const _TopicName = "ancient egyptancient greeceancient chinaancient romemiddle agescrusadesrenaissancescientific revolutionreformationenlightenmentamerican revolutionfrench revolutionnapoleonic warsindustrial revolutionamerican civil warchinese revolutionrussian revolutionworld war iworld war iicold war"

var _TopicIndex = [...]uint16{0, 13, 27, 40, 52, 63, 71, 82, 103, 114, 127, 146, 163, 178, 199, 217, 235, 253, 264, 276, 284}

const _TopicLowerName = "ancient egyptancient greeceancient chinaancient romemiddle agescrusadesrenaissancescientific revolutionreformationenlightenmentamerican revolutionfrench revolutionnapoleonic warsindustrial revolutionamerican civil warchinese revolutionrussian revolutionworld war iworld war iicold war"

func (i Topic) String() string {
	if i < 0 || i >= Topic(len(_TopicIndex)-1) {
		return fmt.Sprintf("Topic(%d)", i)
	}
	return _TopicName[_TopicIndex[i]:_TopicIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TopicNoOp() {
	var x [1]struct{}
	_ = x[TopicAncientEgypt-(0)]
	_ = x[TopicAncientGreece-(1)]
	_ = x[TopicAncientChina-(2)]
	_ = x[TopicAncientRome-(3)]
	_ = x[TopicMiddleAges-(4)]
	_ = x[TopicCrusades-(5)]
	_ = x[TopicRenaissance-(6)]
	_ = x[TopicScientificRevolution-(7)]
	_ = x[TopicReformation-(8)]
	_ = x[TopicEnlightenment-(9)]
	_ = x[TopicAmericanRevolution-(10)]
	_ = x[TopicFrenchRevolution-(11)]
	_ = x[TopicNapoleonicWars-(12)]
	_ = x[TopicIndustrialRevolution-(13)]
	_ = x[TopicAmericanCivilWar-(14)]
	_ = x[TopicChineseRevolution-(15)]
	_ = x[TopicRussianRevolution-(16)]
	_ = x[TopicWorldWarI-(17)]
	_ = x[TopicWorldWarII-(18)]
	_ = x[TopicColdWar-(19)]
}

var _TopicValues = []Topic{TopicAncientEgypt, TopicAncientGreece, TopicAncientChina, TopicAncientRome, TopicMiddleAges, TopicCrusades, TopicRenaissance, TopicScientificRevolution, TopicReformation, TopicEnlightenment, TopicAmericanRevolution, TopicFrenchRevolution, TopicNapoleonicWars, TopicIndustrialRevolution, TopicAmericanCivilWar, TopicChineseRevolution, TopicRussianRevolution, TopicWorldWarI, TopicWorldWarII, TopicColdWar}

var _TopicNameToValueMap = map[string]Topic{
	_TopicName[0:13]:         TopicAncientEgypt,
	_TopicLowerName[0:13]:    TopicAncientEgypt,
	_TopicName[13:27]:        TopicAncientGreece,
	_TopicLowerName[13:27]:   TopicAncientGreece,
	_TopicName[27:40]:        TopicAncientChina,
	_TopicLowerName[27:40]:   TopicAncientChina,
	_TopicName[40:52]:        TopicAncientRome,
	_TopicLowerName[40:52]:   TopicAncientRome,
	_TopicName[52:63]:        TopicMiddleAges,
	_TopicLowerName[52:63]:   TopicMiddleAges,
	_TopicName[63:71]:        TopicCrusades,
	_TopicLowerName[63:71]:   TopicCrusades,
	_TopicName[71:82]:        TopicRenaissance,
	_TopicLowerName[71:82]:   TopicRenaissance,
	_TopicName[82:103]:       TopicScientificRevolution,
	_TopicLowerName[82:103]:  TopicScientificRevolution,
	_TopicName[103:114]:      TopicReformation,
	_TopicLowerName[103:114]: TopicReformation,
	_TopicName[114:127]:      TopicEnlightenment,
	_TopicLowerName[114:127]: TopicEnlightenment,
	_TopicName[127:146]:      TopicAmericanRevolution,
	_TopicLowerName[127:146]: TopicAmericanRevolution,
	_TopicName[146:163]:      TopicFrenchRevolution,
	_TopicLowerName[146:163]: TopicFrenchRevolution,
	_TopicName[163:178]:      TopicNapoleonicWars,
	_TopicLowerName[163:178]: TopicNapoleonicWars,
	_TopicName[178:199]:      TopicIndustrialRevolution,
	_TopicLowerName[178:199]: TopicIndustrialRevolution,
	_TopicName[199:217]:      TopicAmericanCivilWar,
	_TopicLowerName[199:217]: TopicAmericanCivilWar,
	_TopicName[217:235]:      TopicChineseRevolution,
	_TopicLowerName[217:235]: TopicChineseRevolution,
	_TopicName[235:253]:      TopicRussianRevolution,
	_TopicLowerName[235:253]: TopicRussianRevolution,
	_TopicName[253:264]:      TopicWorldWarI,
	_TopicLowerName[253:264]: TopicWorldWarI,
	_TopicName[264:276]:      TopicWorldWarII,
	_TopicLowerName[264:276]: TopicWorldWarII,
	_TopicName[276:284]:      TopicColdWar,
	_TopicLowerName[276:284]: TopicColdWar,
}

var _TopicNames = []string{
	_TopicName[0:13],
	_TopicName[13:27],
	_TopicName[27:40],
	_TopicName[40:52],
	_TopicName[52:63],
	_TopicName[63:71],
	_TopicName[71:82],
	_TopicName[82:103],
	_TopicName[103:114],
	_TopicName[114:127],
	_TopicName[127:146],
	_TopicName[146:163],
	_TopicName[163:178],
	_TopicName[178:199],
	_TopicName[199:217],
	_TopicName[217:235],
	_TopicName[235:253],
	_TopicName[253:264],
	_TopicName[264:276],
	_TopicName[276:284],
}

// TopicString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TopicString(s string) (Topic, error) {
	if val, ok := _TopicNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TopicNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Topic values", s)
}

// TopicValues returns all values of the enum
func TopicValues() []Topic {
	return _TopicValues
}

// TopicStrings returns a slice of all String values of the enum
func TopicStrings() []string {
	strs := make([]string, len(_TopicNames))
	copy(strs, _TopicNames)
	return strs
}

// IsATopic returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Topic) IsATopic() bool {
	for _, v := range _TopicValues {
		if i == v {
			return true
		}
	}
	return false
}
