// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuizoryService_GetLatestQuestions_FullMethodName = "/quizory.QuizoryService/GetLatestQuestions"
	QuizoryService_CreateQuestion_FullMethodName     = "/quizory.QuizoryService/CreateQuestion"
)

// QuizoryServiceClient is the client API for QuizoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuizoryServiceClient interface {
	GetLatestQuestions(ctx context.Context, in *GetLatestQuestionsRequest, opts ...grpc.CallOption) (*GetLatestQuestionsResponse, error)
	CreateQuestion(ctx context.Context, in *CreateQuestionRequest, opts ...grpc.CallOption) (*CreateQuestionResponse, error)
}

type quizoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuizoryServiceClient(cc grpc.ClientConnInterface) QuizoryServiceClient {
	return &quizoryServiceClient{cc}
}

func (c *quizoryServiceClient) GetLatestQuestions(ctx context.Context, in *GetLatestQuestionsRequest, opts ...grpc.CallOption) (*GetLatestQuestionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestQuestionsResponse)
	err := c.cc.Invoke(ctx, QuizoryService_GetLatestQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizoryServiceClient) CreateQuestion(ctx context.Context, in *CreateQuestionRequest, opts ...grpc.CallOption) (*CreateQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateQuestionResponse)
	err := c.cc.Invoke(ctx, QuizoryService_CreateQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuizoryServiceServer is the server API for QuizoryService service.
// All implementations must embed UnimplementedQuizoryServiceServer
// for forward compatibility.
type QuizoryServiceServer interface {
	GetLatestQuestions(context.Context, *GetLatestQuestionsRequest) (*GetLatestQuestionsResponse, error)
	CreateQuestion(context.Context, *CreateQuestionRequest) (*CreateQuestionResponse, error)
	mustEmbedUnimplementedQuizoryServiceServer()
}

// UnimplementedQuizoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuizoryServiceServer struct{}

func (UnimplementedQuizoryServiceServer) GetLatestQuestions(context.Context, *GetLatestQuestionsRequest) (*GetLatestQuestionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestQuestions not implemented")
}
func (UnimplementedQuizoryServiceServer) CreateQuestion(context.Context, *CreateQuestionRequest) (*CreateQuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQuestion not implemented")
}
func (UnimplementedQuizoryServiceServer) mustEmbedUnimplementedQuizoryServiceServer() {}
func (UnimplementedQuizoryServiceServer) testEmbeddedByValue()                        {}

// UnsafeQuizoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuizoryServiceServer will
// result in compilation errors.
type UnsafeQuizoryServiceServer interface {
	mustEmbedUnimplementedQuizoryServiceServer()
}

func RegisterQuizoryServiceServer(s grpc.ServiceRegistrar, srv QuizoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedQuizoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuizoryService_ServiceDesc, srv)
}

func _QuizoryService_GetLatestQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizoryServiceServer).GetLatestQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizoryService_GetLatestQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizoryServiceServer).GetLatestQuestions(ctx, req.(*GetLatestQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuizoryService_CreateQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizoryServiceServer).CreateQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuizoryService_CreateQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizoryServiceServer).CreateQuestion(ctx, req.(*CreateQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuizoryService_ServiceDesc is the grpc.ServiceDesc for QuizoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuizoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quizory.QuizoryService",
	HandlerType: (*QuizoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestQuestions",
			Handler:    _QuizoryService_GetLatestQuestions_Handler,
		},
		{
			MethodName: "CreateQuestion",
			Handler:    _QuizoryService_CreateQuestion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
