/* tslint:disable */
/* eslint-disable */
/**
 * AI Generated Questions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmitAnswerRequest
 */
export interface SubmitAnswerRequest {
    /**
     * 
     * @type {string}
     * @memberof SubmitAnswerRequest
     */
    choiceId: string;
}

/**
 * Check if a given object implements the SubmitAnswerRequest interface.
 */
export function instanceOfSubmitAnswerRequest(value: object): boolean {
    if (!('choiceId' in value)) return false;
    return true;
}

export function SubmitAnswerRequestFromJSON(json: any): SubmitAnswerRequest {
    return SubmitAnswerRequestFromJSONTyped(json, false);
}

export function SubmitAnswerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitAnswerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'choiceId': json['choiceId'],
    };
}

export function SubmitAnswerRequestToJSON(value?: SubmitAnswerRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'choiceId': value['choiceId'],
    };
}

