apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki_ds
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: false

  - name: Prometheus
    type: prometheus
    uid: prometheus_ds
    access: proxy
    url: http://prometheus:9090
    editable: false
