{
 "title": "Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_runtime_go_mem_heap_sys_bytes{exported_job=\"quizory\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Duration (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_duration_milliseconds_sum{exported_job=\"quizory\"}[2m]) / rate(http_server_duration_milliseconds_count{exported_job=\"quizory\"}[2m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Goroutines Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_runtime_go_goroutines{exported_job=\"quizory\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}