{
 "title": "REST API",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "AVG Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (path) (http_request_duration_ms_sum) / sum by (path) (http_request_duration_ms_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status Distribution Over Week",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (increase(http_requests_total[1w]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint Calls",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (path) (http_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}