name: docker
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: sasalatart/quizory-api:${{ github.sha }}
          file: ./infra/docker/Dockerfile
