name: eslint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'pnpm'
          cache-dependency-path: client/pnpm-lock.yaml

      - name: install-dependencies
        run: make install-client

      - name: run-linter
        run: make lint-client
